# Generated by Django 4.2.5 on 2023-09-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
