# Generated by Django 4.2.5 on 2023-10-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
