# Generated by Django 4.2.5 on 2023-10-11 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_movie_bookrating_book_bookauthor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookAuthor',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
    ]
