# Generated by Django 4.2.5 on 2023-09-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tconst', models.CharField(max_length=100)),
                ('titleType', models.CharField(max_length=100)),
                ('primaryTitle', models.CharField(max_length=100)),
                ('originalTitle', models.CharField(max_length=100)),
                ('isAdult', models.BooleanField()),
                ('startYear', models.IntegerField()),
                ('endYear', models.IntegerField()),
                ('runtimeMinutes', models.IntegerField()),
                ('genres', models.CharField(max_length=100)),
            ],
        ),
    ]
